apiVersion: v1
kind: Service
metadata:
  name: hello-k3s-service
spec:
  type: LoadBalancer       # k3s의 ServiceLB가 처리해줍니다.
  selector:
    app: hello-k3s         # 위 Deployment의 labels와 일치해야 연결됩니다.
  ports:
    - protocol: TCP
      port: 8000           # 윈도우 브라우저에서 접속할 포트
      targetPort: 80       # 컨테이너 내부 포트